// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hellovis/ent/predicate"
	"hellovis/ent/studentcheckin"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentCheckinDelete is the builder for deleting a StudentCheckin entity.
type StudentCheckinDelete struct {
	config
	hooks    []Hook
	mutation *StudentCheckinMutation
}

// Where appends a list predicates to the StudentCheckinDelete builder.
func (scd *StudentCheckinDelete) Where(ps ...predicate.StudentCheckin) *StudentCheckinDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *StudentCheckinDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *StudentCheckinDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *StudentCheckinDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(studentcheckin.Table, sqlgraph.NewFieldSpec(studentcheckin.FieldID, field.TypeUUID))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// StudentCheckinDeleteOne is the builder for deleting a single StudentCheckin entity.
type StudentCheckinDeleteOne struct {
	scd *StudentCheckinDelete
}

// Where appends a list predicates to the StudentCheckinDelete builder.
func (scdo *StudentCheckinDeleteOne) Where(ps ...predicate.StudentCheckin) *StudentCheckinDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *StudentCheckinDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{studentcheckin.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *StudentCheckinDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
