// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hellovis/ent/predicate"
	"hellovis/ent/studentcheckout"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentCheckoutDelete is the builder for deleting a StudentCheckout entity.
type StudentCheckoutDelete struct {
	config
	hooks    []Hook
	mutation *StudentCheckoutMutation
}

// Where appends a list predicates to the StudentCheckoutDelete builder.
func (scd *StudentCheckoutDelete) Where(ps ...predicate.StudentCheckout) *StudentCheckoutDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *StudentCheckoutDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *StudentCheckoutDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *StudentCheckoutDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(studentcheckout.Table, sqlgraph.NewFieldSpec(studentcheckout.FieldID, field.TypeUUID))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// StudentCheckoutDeleteOne is the builder for deleting a single StudentCheckout entity.
type StudentCheckoutDeleteOne struct {
	scd *StudentCheckoutDelete
}

// Where appends a list predicates to the StudentCheckoutDelete builder.
func (scdo *StudentCheckoutDeleteOne) Where(ps ...predicate.StudentCheckout) *StudentCheckoutDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *StudentCheckoutDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{studentcheckout.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *StudentCheckoutDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
