// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hellovis/ent/predicate"
	"hellovis/ent/student"
	"hellovis/ent/studentcheckout"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StudentCheckoutUpdate is the builder for updating StudentCheckout entities.
type StudentCheckoutUpdate struct {
	config
	hooks    []Hook
	mutation *StudentCheckoutMutation
}

// Where appends a list predicates to the StudentCheckoutUpdate builder.
func (scu *StudentCheckoutUpdate) Where(ps ...predicate.StudentCheckout) *StudentCheckoutUpdate {
	scu.mutation.Where(ps...)
	return scu
}

// SetUpdatedAt sets the "updated_at" field.
func (scu *StudentCheckoutUpdate) SetUpdatedAt(t time.Time) *StudentCheckoutUpdate {
	scu.mutation.SetUpdatedAt(t)
	return scu
}

// SetDeletedAt sets the "deleted_at" field.
func (scu *StudentCheckoutUpdate) SetDeletedAt(t time.Time) *StudentCheckoutUpdate {
	scu.mutation.SetDeletedAt(t)
	return scu
}

// SetStudentID sets the "student_id" field.
func (scu *StudentCheckoutUpdate) SetStudentID(u uuid.UUID) *StudentCheckoutUpdate {
	scu.mutation.SetStudentID(u)
	return scu
}

// SetStudent sets the "student" edge to the Student entity.
func (scu *StudentCheckoutUpdate) SetStudent(s *Student) *StudentCheckoutUpdate {
	return scu.SetStudentID(s.ID)
}

// Mutation returns the StudentCheckoutMutation object of the builder.
func (scu *StudentCheckoutUpdate) Mutation() *StudentCheckoutMutation {
	return scu.mutation
}

// ClearStudent clears the "student" edge to the Student entity.
func (scu *StudentCheckoutUpdate) ClearStudent() *StudentCheckoutUpdate {
	scu.mutation.ClearStudent()
	return scu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (scu *StudentCheckoutUpdate) Save(ctx context.Context) (int, error) {
	scu.defaults()
	return withHooks(ctx, scu.sqlSave, scu.mutation, scu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scu *StudentCheckoutUpdate) SaveX(ctx context.Context) int {
	affected, err := scu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (scu *StudentCheckoutUpdate) Exec(ctx context.Context) error {
	_, err := scu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scu *StudentCheckoutUpdate) ExecX(ctx context.Context) {
	if err := scu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scu *StudentCheckoutUpdate) defaults() {
	if _, ok := scu.mutation.UpdatedAt(); !ok {
		v := studentcheckout.UpdateDefaultUpdatedAt()
		scu.mutation.SetUpdatedAt(v)
	}
	if _, ok := scu.mutation.DeletedAt(); !ok {
		v := studentcheckout.UpdateDefaultDeletedAt()
		scu.mutation.SetDeletedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scu *StudentCheckoutUpdate) check() error {
	if _, ok := scu.mutation.StudentID(); scu.mutation.StudentCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "StudentCheckout.student"`)
	}
	return nil
}

func (scu *StudentCheckoutUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := scu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(studentcheckout.Table, studentcheckout.Columns, sqlgraph.NewFieldSpec(studentcheckout.FieldID, field.TypeUUID))
	if ps := scu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scu.mutation.UpdatedAt(); ok {
		_spec.SetField(studentcheckout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := scu.mutation.DeletedAt(); ok {
		_spec.SetField(studentcheckout.FieldDeletedAt, field.TypeTime, value)
	}
	if scu.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   studentcheckout.StudentTable,
			Columns: []string{studentcheckout.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scu.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   studentcheckout.StudentTable,
			Columns: []string{studentcheckout.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, scu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studentcheckout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	scu.mutation.done = true
	return n, nil
}

// StudentCheckoutUpdateOne is the builder for updating a single StudentCheckout entity.
type StudentCheckoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudentCheckoutMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (scuo *StudentCheckoutUpdateOne) SetUpdatedAt(t time.Time) *StudentCheckoutUpdateOne {
	scuo.mutation.SetUpdatedAt(t)
	return scuo
}

// SetDeletedAt sets the "deleted_at" field.
func (scuo *StudentCheckoutUpdateOne) SetDeletedAt(t time.Time) *StudentCheckoutUpdateOne {
	scuo.mutation.SetDeletedAt(t)
	return scuo
}

// SetStudentID sets the "student_id" field.
func (scuo *StudentCheckoutUpdateOne) SetStudentID(u uuid.UUID) *StudentCheckoutUpdateOne {
	scuo.mutation.SetStudentID(u)
	return scuo
}

// SetStudent sets the "student" edge to the Student entity.
func (scuo *StudentCheckoutUpdateOne) SetStudent(s *Student) *StudentCheckoutUpdateOne {
	return scuo.SetStudentID(s.ID)
}

// Mutation returns the StudentCheckoutMutation object of the builder.
func (scuo *StudentCheckoutUpdateOne) Mutation() *StudentCheckoutMutation {
	return scuo.mutation
}

// ClearStudent clears the "student" edge to the Student entity.
func (scuo *StudentCheckoutUpdateOne) ClearStudent() *StudentCheckoutUpdateOne {
	scuo.mutation.ClearStudent()
	return scuo
}

// Where appends a list predicates to the StudentCheckoutUpdate builder.
func (scuo *StudentCheckoutUpdateOne) Where(ps ...predicate.StudentCheckout) *StudentCheckoutUpdateOne {
	scuo.mutation.Where(ps...)
	return scuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (scuo *StudentCheckoutUpdateOne) Select(field string, fields ...string) *StudentCheckoutUpdateOne {
	scuo.fields = append([]string{field}, fields...)
	return scuo
}

// Save executes the query and returns the updated StudentCheckout entity.
func (scuo *StudentCheckoutUpdateOne) Save(ctx context.Context) (*StudentCheckout, error) {
	scuo.defaults()
	return withHooks(ctx, scuo.sqlSave, scuo.mutation, scuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scuo *StudentCheckoutUpdateOne) SaveX(ctx context.Context) *StudentCheckout {
	node, err := scuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (scuo *StudentCheckoutUpdateOne) Exec(ctx context.Context) error {
	_, err := scuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scuo *StudentCheckoutUpdateOne) ExecX(ctx context.Context) {
	if err := scuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scuo *StudentCheckoutUpdateOne) defaults() {
	if _, ok := scuo.mutation.UpdatedAt(); !ok {
		v := studentcheckout.UpdateDefaultUpdatedAt()
		scuo.mutation.SetUpdatedAt(v)
	}
	if _, ok := scuo.mutation.DeletedAt(); !ok {
		v := studentcheckout.UpdateDefaultDeletedAt()
		scuo.mutation.SetDeletedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scuo *StudentCheckoutUpdateOne) check() error {
	if _, ok := scuo.mutation.StudentID(); scuo.mutation.StudentCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "StudentCheckout.student"`)
	}
	return nil
}

func (scuo *StudentCheckoutUpdateOne) sqlSave(ctx context.Context) (_node *StudentCheckout, err error) {
	if err := scuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(studentcheckout.Table, studentcheckout.Columns, sqlgraph.NewFieldSpec(studentcheckout.FieldID, field.TypeUUID))
	id, ok := scuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StudentCheckout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := scuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studentcheckout.FieldID)
		for _, f := range fields {
			if !studentcheckout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != studentcheckout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := scuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scuo.mutation.UpdatedAt(); ok {
		_spec.SetField(studentcheckout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := scuo.mutation.DeletedAt(); ok {
		_spec.SetField(studentcheckout.FieldDeletedAt, field.TypeTime, value)
	}
	if scuo.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   studentcheckout.StudentTable,
			Columns: []string{studentcheckout.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := scuo.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   studentcheckout.StudentTable,
			Columns: []string{studentcheckout.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StudentCheckout{config: scuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, scuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studentcheckout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	scuo.mutation.done = true
	return _node, nil
}
