// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hellovis/ent/predicate"
	"hellovis/ent/studentcheckout"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StudentCheckoutQuery is the builder for querying StudentCheckout entities.
type StudentCheckoutQuery struct {
	config
	ctx        *QueryContext
	order      []studentcheckout.OrderOption
	inters     []Interceptor
	predicates []predicate.StudentCheckout
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StudentCheckoutQuery builder.
func (scq *StudentCheckoutQuery) Where(ps ...predicate.StudentCheckout) *StudentCheckoutQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *StudentCheckoutQuery) Limit(limit int) *StudentCheckoutQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *StudentCheckoutQuery) Offset(offset int) *StudentCheckoutQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *StudentCheckoutQuery) Unique(unique bool) *StudentCheckoutQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *StudentCheckoutQuery) Order(o ...studentcheckout.OrderOption) *StudentCheckoutQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// First returns the first StudentCheckout entity from the query.
// Returns a *NotFoundError when no StudentCheckout was found.
func (scq *StudentCheckoutQuery) First(ctx context.Context) (*StudentCheckout, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{studentcheckout.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *StudentCheckoutQuery) FirstX(ctx context.Context) *StudentCheckout {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StudentCheckout ID from the query.
// Returns a *NotFoundError when no StudentCheckout ID was found.
func (scq *StudentCheckoutQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{studentcheckout.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *StudentCheckoutQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StudentCheckout entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StudentCheckout entity is found.
// Returns a *NotFoundError when no StudentCheckout entities are found.
func (scq *StudentCheckoutQuery) Only(ctx context.Context) (*StudentCheckout, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{studentcheckout.Label}
	default:
		return nil, &NotSingularError{studentcheckout.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *StudentCheckoutQuery) OnlyX(ctx context.Context) *StudentCheckout {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StudentCheckout ID in the query.
// Returns a *NotSingularError when more than one StudentCheckout ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *StudentCheckoutQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{studentcheckout.Label}
	default:
		err = &NotSingularError{studentcheckout.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *StudentCheckoutQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StudentCheckouts.
func (scq *StudentCheckoutQuery) All(ctx context.Context) ([]*StudentCheckout, error) {
	ctx = setContextOp(ctx, scq.ctx, "All")
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StudentCheckout, *StudentCheckoutQuery]()
	return withInterceptors[[]*StudentCheckout](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *StudentCheckoutQuery) AllX(ctx context.Context) []*StudentCheckout {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StudentCheckout IDs.
func (scq *StudentCheckoutQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, "IDs")
	if err = scq.Select(studentcheckout.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *StudentCheckoutQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *StudentCheckoutQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, "Count")
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*StudentCheckoutQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *StudentCheckoutQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *StudentCheckoutQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, "Exist")
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *StudentCheckoutQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StudentCheckoutQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *StudentCheckoutQuery) Clone() *StudentCheckoutQuery {
	if scq == nil {
		return nil
	}
	return &StudentCheckoutQuery{
		config:     scq.config,
		ctx:        scq.ctx.Clone(),
		order:      append([]studentcheckout.OrderOption{}, scq.order...),
		inters:     append([]Interceptor{}, scq.inters...),
		predicates: append([]predicate.StudentCheckout{}, scq.predicates...),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StudentCheckout.Query().
//		GroupBy(studentcheckout.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *StudentCheckoutQuery) GroupBy(field string, fields ...string) *StudentCheckoutGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StudentCheckoutGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = studentcheckout.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StudentCheckout.Query().
//		Select(studentcheckout.FieldCreatedAt).
//		Scan(ctx, &v)
func (scq *StudentCheckoutQuery) Select(fields ...string) *StudentCheckoutSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &StudentCheckoutSelect{StudentCheckoutQuery: scq}
	sbuild.label = studentcheckout.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StudentCheckoutSelect configured with the given aggregations.
func (scq *StudentCheckoutQuery) Aggregate(fns ...AggregateFunc) *StudentCheckoutSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *StudentCheckoutQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !studentcheckout.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *StudentCheckoutQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StudentCheckout, error) {
	var (
		nodes = []*StudentCheckout{}
		_spec = scq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StudentCheckout).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StudentCheckout{config: scq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (scq *StudentCheckoutQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *StudentCheckoutQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(studentcheckout.Table, studentcheckout.Columns, sqlgraph.NewFieldSpec(studentcheckout.FieldID, field.TypeUUID))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studentcheckout.FieldID)
		for i := range fields {
			if fields[i] != studentcheckout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *StudentCheckoutQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(studentcheckout.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = studentcheckout.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StudentCheckoutGroupBy is the group-by builder for StudentCheckout entities.
type StudentCheckoutGroupBy struct {
	selector
	build *StudentCheckoutQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *StudentCheckoutGroupBy) Aggregate(fns ...AggregateFunc) *StudentCheckoutGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *StudentCheckoutGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, "GroupBy")
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StudentCheckoutQuery, *StudentCheckoutGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *StudentCheckoutGroupBy) sqlScan(ctx context.Context, root *StudentCheckoutQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StudentCheckoutSelect is the builder for selecting fields of StudentCheckout entities.
type StudentCheckoutSelect struct {
	*StudentCheckoutQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *StudentCheckoutSelect) Aggregate(fns ...AggregateFunc) *StudentCheckoutSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *StudentCheckoutSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, "Select")
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StudentCheckoutQuery, *StudentCheckoutSelect](ctx, scs.StudentCheckoutQuery, scs, scs.inters, v)
}

func (scs *StudentCheckoutSelect) sqlScan(ctx context.Context, root *StudentCheckoutQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
