// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// StudentCheckin is the predicate function for studentcheckin builders.
type StudentCheckin func(*sql.Selector)

// StudentCheckout is the predicate function for studentcheckout builders.
type StudentCheckout func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
