name: CI - backend
on:
  push:
    branches:
      - main
    paths:
      - server/src/**
      - .github/workflows/ci.yml
      - "!README.md"
  pull_request:
    paths:
      - server/src/**
      - .github/workflows/ci.yml
      - "!README.md"

defaults:
  run:
    working-directory: server/src

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: server/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: server/go.sum
      - name: Format check
        run: make fmt-check

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      - uses: actions/setup-go@v3
        with:
          go-version-file: "server/src/go.mod"
          check-latest: true
          cache: true
          cache-dependency-path: server/src/go.sum
      - name: Test
        run: go test $(go list ./... | grep -v -e /ent) -cover -coverprofile=cover.out
      - name: Upload Coverage Report
        run: go tool cover -html=cover.out -o cover.html
      - name: UploadReport
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: server/src/cover.html
          retention-days: 7
      - name: Build
        run: go build main.go

    static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'server/go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: server/go.sum
      - name: Generate Mock
        run: make mock
      - name: Check Mock diff
        run: git add . && git diff --cached --quiet
      - name: Show Mock diff if failure
        if: ${{ failure() }}
        run: git diff --cached
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: server
          # https://github.com/golangci/golangci-lint-action/issues/244
          skip-pkg-cache: true
          args: --timeout=3m
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.51.2
      # https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981133649
      - name: Show Lint Errors
        run: golangci-lint run
        if: ${{ failure() }}
